### ISSUE TITLE
Use Dockerfile to construct containers

### ISSUE THREAD

**Issue by ChrisTimperley** [gavanderhoorn/rosin_bug_hunt_l3#1] opened 2017-11-20 13:43 UTC
At the moment, containers are being built by passing a ROS install package file to `docker run`:

```
# setup and populate workspace
docker run -it --rm \
  -u $(id -u):$(id -g) \
  -v ${ROS_WS}:/ros_ws \
  -v ${ROSINSTALL_FILE}:/tmp/pkgs.rosinstall \
  ${DOCKER_IMAGE} \
    bash -c '\
      wstool init /ros_ws/src /tmp/pkgs.rosinstall && \
      cd /ros_ws && \
      catkin_make
```

Instead, we should use an individual Dockerfile to build each bug:

```
FROM BASE_IMAGE
ADD pkgs.rosinstall
RUN wstool init /ros_ws/src /tmp/pkgs.rosinstall && \
      cd /ros_ws && \
      catkin_make
```

The Dockerfile should be located in a directory named after the first eight characters of commit hash. Of course, using this approach we will end up with a large number of identical Dockerfiles scattered across the file system. To correct that, we could write the contents of the above file to a `Dockerfile.basic`, located at the root of directory containing all of the bugs. We could then use a simple Python script to build the containers via Docker's Python API:

```
#!/usr/bin/env python3
import docker
import shutil
import os

all_bugs_dir = ....
base_dockerfn = os.path.join(all_bugs_dir, 'Dockerfile.basic')

docker_client = docker.from_env()

def build_bug_image(rev):
    # copy the base Dockerfile to the bug directory (since Dockerfile must be in build context)
    rev_dir = os.path.join(all_bugs_dir, rev_dir)
    rev_dockerfn = os.path.join(rev_dir, '.Dockerfile)
    shutil.copy(base_dockerfn, rev_dockerfn)

    # build the image
    try:
        client.images.build(path=rev_dir, dockerfile='.Dockerfile')

    # destroy the temporary Dockerfile
    finally:
        os.remove(rev_dockerfn)
```

**Comment by gavanderhoorn** [comment] 2017-11-20 14:08
Thanks for the suggestion.

If I understand you correctly your proposed approach would mean that we have the workspace as a directory *inside* the image, correct?

The current implementation assumes that we want to keep it on the host.

Assumption on my part is that that makes it easier for automated tools to reach into the workspace, identify the cause of the bug, potentially fix it and then the workspace could be rebuilt (using a similar Docker command, but without seeding the workspace again using `wstool`).

**Comment by gavanderhoorn** [comment] 2017-11-20 14:11
We will probably need to build custom images for more complex bugs btw (with dependencies not provided by any existing image(s)), so there your approach (or a similar one) would probably be needed.

**Comment by ChrisTimperley** [comment] 2017-11-23 03:16
Yeah, that's right @gavanderhoorn.

That's a fair assumption and that would definitely make it easier to work with the image. I believe that we should be to achieve the same intent by using volume mounting, which would allow us to use a Dockerfile-based approach. In that case, when provisioning the Docker container, users would use volume mounting to share the workspace between the container and the host. The `run` command would look something like:

```
docker run --rm -v ${PWD}/ros_ws:/ros_ws -it
```

**Comment by gavanderhoorn** [comment] 2017-11-23 07:14
The `run_tests.sh` script currently mounts the ROS workspace like so:

```shell
docker run -it --rm \
  ...
  -v ${ROS_WS}:/ros_ws \
  ...
```
Is that what you are suggesting?

> which would allow us to use a Dockerfile-based approach. In that case, when provisioning the Docker container, users would use volume mounting to share the workspace between the container and the host. 

I'm confused about the 'provisioning' part here: we're currently using the OSRF provided `ros-lunar-ros-core` image, but that is probably not the best choice (as it's a moving target). That is something we'd have to fix, and I imagine we'll build our own custom (or at least 'frozen') images, indeed.

**Comment by gavanderhoorn** [comment] 2017-11-24 14:12
@wasowski @git-afsantos

**Comment by ChrisTimperley** [comment] 2017-11-29 17:28
@gavanderhoorn we would build an image for the bug that we're interested in, rather than starting from a base image and rerunning build commands every time we interact with that bug (which is redundant and equivalent to using the "FROM" command in a Dockerfile).

My example bug over on BitBucket should provide an example of what I mean.

**Comment by gavanderhoorn** [comment] 2017-11-29 21:55
So I guess you'd like an image that contains all the dependencies, but not the actual workspace itself?

And with dependencies I would then also mean the built-from-sources pkgs that are not directly hosting any of the files that are part of the bug?

**Comment by gavanderhoorn** [comment] 2017-11-29 21:55
I believe not having the (entire) workspace being part of the image is a very valuable thing, so I'd like to avoid that (but not at all costs).

Having everything in the image does not make sense to me right now.

**Comment by ChrisTimperley** [comment] 2017-11-29 22:34
No, I'd like to have an image that contains both the dependencies and the workspace -- it should contain everything that's needed to build and run the software (in simulation). Anything that is external to the Docker image is outside of our control and therefore isn't reproducible.

**Comment by gavanderhoorn** [comment] 2017-11-29 22:41
But which software would you still want to build if everything is already in the image?

**Comment by gavanderhoorn** [comment] 2017-11-29 22:44
'everything that is needed' would be the dependencies (including the ros pkgs that we'd need to build from sources).

'to run the software' is essentially all the nodes involved in the bug, being hosted by the pkgs in the workspace.

There isn't much else, unless I'm completely misunderstanding you.

> Anything that is external to the Docker image is outside of our control and therefore isn't reproducible.

if the versions of the pkgs that we build are determined by the commit hashes specified in the `.rosinstall` files, and all dependencies (and compiler, etc) are in the image, then what is outside of our control still?

**Comment by gavanderhoorn** [comment] 2017-11-29 22:46
Would you like to avoid having to build the pkg under test / part of the bug as well? Or do you see a benefit in having the sources of the pkg under test / part of the bug in the container?

**Comment by ChrisTimperley** [comment] 2017-11-29 23:13
It seems like we're both in agreement over what should be contained within the image.

> 'everything that is needed' would be the dependencies (including the ros pkgs that we'd need to build from sources).
 'to run the software' is essentially all the nodes involved in the bug, being hosted by the pkgs in the workspace.

Exactly.

> if the versions of the pkgs that we build are determined by the commit hashes specified in the .rosinstall files, and all dependencies (and compiler, etc) are in the image, then what is outside of our control still?

That seems to be sufficient.

> Would you like to avoid having to build the pkg under test / part of the bug as well? Or do you see a benefit in having the sources of the pkg under test / part of the bug in the container?

Nah, I think we should try to build the package under test where possible; I'm not sure what we sure do with compilation bugs, though.

**Comment by gavanderhoorn** [comment] 2018-01-03 15:18
I've created a candidate `Dockerfile` for this. See [rosin_bug_hunt_l3/tree/l3_time_machine_tf2_ros](https://github.com/gavanderhoorn/rosin_bug_hunt_l3/tree/l3_time_machine_tf2_ros).

**Comment by ChrisTimperley** [comment] 2018-01-03 15:45
@gavanderhoorn That looks great!

**Comment by wasowski** [comment] 2018-01-04 09:50
FYI: better late than never. I have seen this and trying to use on my case.

**Comment by gavanderhoorn** [comment] 2018-01-04 09:53
@wasowski wrote:
> FYI: better late than never.

?

**Comment by wasowski** [comment] 2018-01-04 10:12
You CC'ed me on this almost 2 month ago. At my usual speed I realized the usefulness of this :) [I always believed this is a good thing, but now I actually need it to handle my bugs in tf2, as you know from the other thread]

**Comment by gavanderhoorn** [comment] 2018-05-18 06:49
This is all being done (and more !) in [robust-rosin/robust](https://github.com/robust-rosin/robust), so closing.

**Closed as completed by gavanderhoorn** 2018-05-18 06:49 UTC
